language: go

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - cd $GOPATH/src/github.com/d3r0/gorgbmatrix/vendor/rpi-rgb-led-matrix/
  - git submodule update --init
  - make 
  - cd $GOPATH/src/github.com/d3r0/gorgbmatrix/
  - go get -t -v ./...
  - go install -v ./...
